# Generated by Django 5.2 on 2025-04-24 13:11

import cloudinary.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên file gốc')),
                ('filePath', cloudinary.models.CloudinaryField(max_length=255, verbose_name='File CV')),
                ('versionName', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tên phiên bản (e.g., CV Tiếng Anh)')),
                ('uploadDate', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tải lên')),
                ('isDefault', models.BooleanField(default=False, verbose_name='Là CV mặc định')),
            ],
            options={
                'verbose_name': 'CV',
                'verbose_name_plural': 'Các CV',
            },
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề công việc')),
                ('description', models.TextField(verbose_name='Mô tả công việc')),
                ('location', models.CharField(max_length=255, verbose_name='Địa điểm làm việc')),
                ('salaryMin', models.FloatField(blank=True, null=True, verbose_name='Lương tối thiểu')),
                ('salaryMax', models.FloatField(blank=True, null=True, verbose_name='Lương tối đa')),
                ('experienceRequired', models.CharField(blank=True, max_length=100, null=True, verbose_name='Kinh nghiệm yêu cầu')),
                ('jobType', models.CharField(choices=[('Full-time', 'Toàn thời gian'), ('Part-time', 'Bán thời gian'), ('Freelance', 'Freelance'), ('Internship', 'Thực tập')], max_length=20, verbose_name='Loại hình công việc')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đăng')),
                ('expiresAt', models.DateTimeField(blank=True, null=True, verbose_name='Ngày hết hạn')),
                ('isActive', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
            ],
            options={
                'verbose_name': 'Tin tuyển dụng',
                'verbose_name_plural': 'Các tin tuyển dụng',
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('avatar', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Ảnh đại diện')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Người dùng',
                'verbose_name_plural': 'Người dùng',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roleName', models.CharField(choices=[('NTV', 'Người tìm việc'), ('NTD', 'Nhà tuyển dụng'), ('Admin', 'Quản trị viên')], max_length=20, unique=True, verbose_name='Tên vai trò')),
            ],
            options={
                'verbose_name': 'Vai trò',
                'verbose_name_plural': 'Các vai trò',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submittedAt', models.DateTimeField(auto_now_add=True, verbose_name='Ngày ứng tuyển')),
                ('status', models.CharField(choices=[('Applied', 'Đã ứng tuyển'), ('Viewed', 'NTD đã xem'), ('Interviewing', 'Đang phỏng vấn'), ('Offered', 'Đã mời nhận việc'), ('Rejected', 'Đã từ chối'), ('Withdrawn', 'Ứng viên đã rút')], default='Applied', max_length=20, verbose_name='Trạng thái')),
                ('coverLetter', models.TextField(blank=True, null=True, verbose_name='Thư xin việc')),
                ('cv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='Recruitments.cv', verbose_name='CV đã sử dụng')),
                ('job_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='Recruitments.jobposting', verbose_name='Tin tuyển dụng')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='Người ứng tuyển (NTV)')),
            ],
            options={
                'verbose_name': 'Hồ sơ ứng tuyển',
                'verbose_name_plural': 'Các hồ sơ ứng tuyển',
                'ordering': ['-submittedAt'],
                'unique_together': {('user', 'job_posting')},
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduledTime', models.DateTimeField(verbose_name='Thời gian dự kiến')),
                ('platformLink', models.URLField(blank=True, null=True, verbose_name='Link phòng họp video')),
                ('status', models.CharField(choices=[('Scheduled', 'Đã lên lịch'), ('Completed', 'Đã hoàn thành'), ('Cancelled', 'Đã hủy')], default='Scheduled', max_length=20, verbose_name='Trạng thái')),
                ('notesNtd', models.TextField(blank=True, null=True, verbose_name='Ghi chú của NTD')),
                ('notesNtv', models.TextField(blank=True, null=True, verbose_name='Ghi chú của NTV')),
                ('result', models.CharField(blank=True, choices=[('Passed', 'Đạt'), ('Failed', 'Không đạt'), ('Pending', 'Chờ kết quả')], default='Pending', max_length=20, null=True, verbose_name='Kết quả')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='Recruitments.application', verbose_name='Hồ sơ ứng tuyển')),
            ],
            options={
                'verbose_name': 'Buổi phỏng vấn',
                'verbose_name_plural': 'Các buổi phỏng vấn',
                'ordering': ['scheduledTime'],
            },
        ),
        migrations.CreateModel(
            name='NtdProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ntdprofile', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
                ('companyName', models.CharField(max_length=255, verbose_name='Tên công ty')),
                ('companyWebsite', models.URLField(blank=True, null=True, verbose_name='Website công ty')),
                ('companyDescription', models.TextField(blank=True, null=True, verbose_name='Mô tả công ty')),
                ('industry', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ngành nghề')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Địa chỉ công ty')),
                ('companyLogo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Logo công ty')),
            ],
            options={
                'verbose_name': 'Hồ sơ Nhà tuyển dụng',
                'verbose_name_plural': 'Các hồ sơ Nhà tuyển dụng',
            },
        ),
        migrations.CreateModel(
            name='NtvProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ntvprofile', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='Giới thiệu bản thân')),
                ('experience', models.TextField(blank=True, null=True, verbose_name='Kinh nghiệm làm việc')),
                ('education', models.TextField(blank=True, null=True, verbose_name='Học vấn')),
                ('skills', models.TextField(blank=True, null=True, verbose_name='Kỹ năng (phân cách bởi dấu phẩy)')),
                ('phoneNumber', models.CharField(blank=True, max_length=15, null=True, verbose_name='Số điện thoại')),
                ('dateOfBirth', models.DateField(blank=True, null=True, verbose_name='Ngày sinh')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Nam'), ('F', 'Nữ'), ('O', 'Khác')], max_length=1, null=True, verbose_name='Giới tính')),
            ],
            options={
                'verbose_name': 'Hồ sơ Người tìm việc',
                'verbose_name_plural': 'Các hồ sơ Người tìm việc',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Nội dung thông báo')),
                ('type', models.CharField(choices=[('NewJob', 'Việc làm mới phù hợp'), ('StatusUpdate', 'Cập nhật trạng thái ứng tuyển'), ('InterviewReminder', 'Nhắc lịch phỏng vấn'), ('ChatMessage', 'Tin nhắn mới'), ('System', 'Thông báo hệ thống')], max_length=20, verbose_name='Loại thông báo')),
                ('relatedUrl', models.URLField(blank=True, null=True, verbose_name='URL liên quan')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('isRead', models.BooleanField(default=False, verbose_name='Đã đọc')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Người nhận')),
            ],
            options={
                'verbose_name': 'Thông báo',
                'verbose_name_plural': 'Các thông báo',
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastMessageAt', models.DateTimeField(auto_now=True, verbose_name='Thời gian tin nhắn cuối')),
                ('participants', models.ManyToManyField(related_name='conversations', to=settings.AUTH_USER_MODEL, verbose_name='Người tham gia')),
            ],
            options={
                'verbose_name': 'Cuộc hội thoại',
                'verbose_name_plural': 'Các cuộc hội thoại',
                'ordering': ['-lastMessageAt'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Nội dung')),
                ('sentAt', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian gửi')),
                ('isRead', models.BooleanField(default=False, verbose_name='Đã đọc')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='Recruitments.conversation', verbose_name='Cuộc hội thoại')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Người gửi')),
            ],
            options={
                'verbose_name': 'Tin nhắn',
                'verbose_name_plural': 'Các tin nhắn',
                'ordering': ['sentAt'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='activeRole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Recruitments.role', verbose_name='Vai trò đang hoạt động'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='ntd_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to='Recruitments.ntdprofile', verbose_name='Hồ sơ NTD'),
        ),
        migrations.AddField(
            model_name='cv',
            name='ntv_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cvs', to='Recruitments.ntvprofile', verbose_name='Hồ sơ NTV'),
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isApproved', models.BooleanField(default=False, verbose_name='Đã phê duyệt (cho NTD)')),
                ('approvedAt', models.DateTimeField(blank=True, null=True, verbose_name='Ngày phê duyệt')),
                ('approvedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_roles', to=settings.AUTH_USER_MODEL, verbose_name='Người phê duyệt')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_users', to='Recruitments.role', verbose_name='Vai trò')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Vai trò người dùng',
                'verbose_name_plural': 'Các vai trò người dùng',
                'unique_together': {('user', 'role')},
            },
        ),
    ]
