# Generated by Django 5.2 on 2025-05-11 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recruitments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['user__username'], 'verbose_name': 'Đơn ứng tuyển', 'verbose_name_plural': 'Các đơn ứng tuyển'},
        ),
        migrations.AlterModelOptions(
            name='cv',
            options={'ordering': ['file_name'], 'verbose_name': 'CV', 'verbose_name_plural': 'Các CV'},
        ),
        migrations.AlterModelOptions(
            name='interview',
            options={'ordering': ['scheduled_time'], 'verbose_name': 'Cuộc phỏng vấn', 'verbose_name_plural': 'Các cuộc phỏng vấn'},
        ),
        migrations.AlterModelOptions(
            name='jobposting',
            options={'ordering': ['created_at'], 'verbose_name': 'Bài đăng tuyển dụng', 'verbose_name_plural': 'Các bài đăng tuyển dụng'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at'], 'verbose_name': 'Tin nhắn', 'verbose_name_plural': 'Các tin nhắn'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['created_at'], 'verbose_name': 'Thông báo', 'verbose_name_plural': 'Các thông báo'},
        ),
        migrations.AlterModelOptions(
            name='ntdprofile',
            options={'ordering': ['company_name'], 'verbose_name': 'Hồ sơ Nhà tuyển dụng', 'verbose_name_plural': 'Hồ sơ Nhà tuyển dụng'},
        ),
        migrations.AlterModelOptions(
            name='ntvprofile',
            options={'ordering': ['user__username'], 'verbose_name': 'Hồ sơ Người tìm việc', 'verbose_name_plural': 'Hồ sơ Người tìm việc'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['role_name'], 'verbose_name': 'Vai trò', 'verbose_name_plural': 'Các vai trò'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['name'], 'verbose_name': 'Kỹ năng', 'verbose_name_plural': 'Các kỹ năng'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username'], 'verbose_name': 'Người dùng', 'verbose_name_plural': 'Người dùng'},
        ),
        migrations.AlterModelOptions(
            name='userrole',
            options={'ordering': ['user__username'], 'verbose_name': 'Vai trò người dùng', 'verbose_name_plural': 'Các vai trò người dùng'},
        ),
        migrations.AddField(
            model_name='jobposting',
            name='status',
            field=models.CharField(choices=[('draft', 'Nháp'), ('pending_approval', 'Chờ phê duyệt'), ('approved', 'Đã phê duyệt')], default='draft', max_length=20),
        ),
    ]
