# Generated by Django 5.2 on 2025-05-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recruitments', '0002_remove_conversation_participants_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='isActive',
            field=models.BooleanField(default=False, verbose_name='Đang hoạt động'),
        ),
    ]
