# Generated by Django 5.2 on 2025-05-11 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recruitments', '0002_alter_application_options_alter_cv_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='status',
            field=models.CharField(choices=[('draft', 'Nháp'), ('pending_approval', 'Chờ phê duyệt'), ('approved', 'Đã phê duyệt'), ('closed', 'Đã đóng')], default='draft', max_length=20),
        ),
    ]
