# Generated by Django 5.2 on 2025-05-11 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recruitments', '0003_jobposting_expiration_date_alter_jobposting_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='interview',
            unique_together={('application',)},
        ),
    ]
